apiVersion: v1
kind: Service
metadata:
  name: giropops-senhas
  namespace: giropops-senhas
  annotations:
    prometheus.io/port: "8000"
    prometheus.io/scrape: "true"
  labels:
    app: giropops-senhas
spec:
  selector:
    app: giropops-senhas
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: tcp-app
  type: ClusterIP